### ISSUE TITLE
Grant @kenmclea and @elizishere write access to GitHub repo so they can edit ZenHub issues

### ISSUE THREAD

**Issue by jwarrenbc** [bcgov/employee-relations#12]

**Comment by jwarrenbc** [comment]
It will take a few hours for ZenHub to pick up the permission change from GitHub.

**Comment by warrenchristian1telus** [comment]
@freshjwarren I have added both accounts with Triage access on the repo. Ken doesn't appear to be a member of BCDevOps yet, so I have sent a request to have him added. I selected Triage access, which should give them enough access to manage issues in ZenHub. If they need write access to the repo, please let me know (re-open this ticket), and I can adjust.
