### ISSUE TITLE
Issue Requires Approval to Open Case File

### ISSUE THREAD

**Issue by nicolemichael** [bcgov/employee-relations#56]

**Comment by nicolemichael** [comment]
[https://app.zenhub.com/files/435673187/714df365-9e15-4eed-a24f-d95355370286/download](https://app.zenhub.com/files/435673187/714df365-9e15-4eed-a24f-d95355370286/download)

**Comment by warrenchristian1telus** [comment]
Hi @nicolemichael - Maybe we could add some clarity on what is actionable here? The document above illustrates current process, but I don't see any changes outlined.

If it is considered an issue that a new issue requires an approver, I think using the user adding themselves as approver may resolve it. In that case, the change would only be procedure, and not require any development.

**Comment by warrenchristian1telus** [comment]
@nicolemichael My recommendation is to close this issue. I think that the user approving their own will satisfy this requirement. If there are more changes / customizations required, then we'll need to determine what they are to make this actionable. Please feel free to close this, or add any additional requirements.
